additionalPolicies:
  master: |
    [
      {
        "Effect": "Allow",
        "Action": ["ec2:*"],
        "Resource": ["*"]
      },
      {
        "Effect": "Allow",
        "Action": ["iam:*"],
        "Resource": ["*"]
      },
      {
        "Effect": "Allow",
        "Action": ["ecr:*"],
        "Resource": ["*"]
      }
    ]
