
name: Deploy-ECR

on:
  push:
    branches: ["dev"]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # AWS ENV
  AWS_REGION: eu-central-1 # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Build the docker images
        docker compose build
        docker build -t $ECR_REGISTRY/react-backend:1.0.0 -t $ECR_REGISTRY/react-backend:latest ./backend/
        docker build -t $ECR_REGISTRY/react-frontend:1.0.0 -t $ECR_REGISTRY/react-frontend:latest ./frontend/

        #echo "$GITHUB_OUTPUT"
