
name: Destroy KOPS Cluster
on:
  #push:
  #  branches: ["dev"]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1
  KOPS_PROVIDER: aws
  KOPS_BUCKET_STATE: ${{ vars.KOPS_BUCKET_STATE }}
  KOPS_BUCKET_OIDC_STORE: ${{ vars.KOPS_BUCKET_OIDC_STORE }} # not in use
  KOPS_CLUSTER_NAME: ${{ vars.KOPS_CLUSTER_NAME }}
  KOPS_DNS_ZONE: ${{ vars.KOPS_DNS_ZONE }}
  KOPS_CLUSTER_ZONES: us-east-1a # set this to your preferred AWS availability zones, e.g. us-west-1a,us-west-1b,us-west-1c
  #,us-east-1b,us-east-1c  # you can specify multiple zones separated by commas if you want to create a multi-zone cluster
  KOPS_MASTER_INSTANCE_SIZE: t3.large # set this to your preferred master node instance size, e.g. t3.large
  KOPS_NODE_INSTANCE_SIZE: t3.xlarge # set this to your preferred node instance size, e.g. t3.xlarge , prometheus-stack requires t3.xlarge
  KOPS_NODE_COUNT: 2 # set this to your preferred node count, e.g. 2

permissions:
  contents: read

jobs:
  destroy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: install kops
      run: |
        # install kops
        sudo apt-get update
        curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
        chmod +x kops
        sudo mv kops /usr/local/bin/kops       
    
    - name : delete kops cluster
      run: |
        # export KOPS env variables
        export KOPS_CLUSTER_NAME=${{ env.KOPS_CLUSTER_NAME }}
        export KOPS_PROVIDER=${{ env.KOPS_PROVIDER }}
        export KOPS_STATE_STORE=s3://${{ env.KOPS_BUCKET_STATE }}
        export KOPS_DISCOVERY_STORE=s3://${{ env.KOPS_BUCKET_OIDC_STORE }}
        export KOPS_DNS_ZONE=${{ env.KOPS_DNS_ZONE }}
        export KOPS_CLUSTER_ZONES=${{ env.KOPS_CLUSTER_ZONES }}

        # delete kops cluster
        kops delete cluster --name ${KOPS_CLUSTER_NAME} --yes




